# Map services used when a player uses command '/where' Options are Google, Yandex, OSM
MapLinks:
  - Google
  - Yandex
  - OSM

# Whether to show the player's height (Y-level + HeightOffset) in the action bar
ShowHeightInActionBar: true

# Offset added to the height display and when a player specifies a height in /tpll command
HeightOffset: 0
