# Map services used when a player uses command '/where' Options are Google, Yandex, OSM
MapLinks:
  - Google
  - Yandex
  - OSM

# Offset added to the height when a player specifies a height in /tpll command
HeightOffset: 0
